# Generated by Django 3.2.4 on 2021-10-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdes', models.CharField(max_length=500)),
                ('picture', models.ImageField(default='', upload_to='static/gallery')),
                ('gdate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='gallary',
        ),
    ]
