# Generated by Django 3.2.4 on 2021-10-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notifiction_slider_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notifiction',
            new_name='notification',
        ),
    ]
