# Generated by Django 4.0.2 on 2022-06-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_notifiction_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('paddre', models.CharField(max_length=50)),
                ('whereto', models.CharField(max_length=50)),
                ('arrival', models.CharField(max_length=20)),
                ('howmany', models.CharField(max_length=20)),
                ('leaving', models.CharField(max_length=20)),
                ('ppic', models.ImageField(default='', upload_to='static/category/')),
                ('msj', models.CharField(max_length=600)),
            ],
        ),
    ]
